name: facts_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  adaptive_action_sheet: ^2.0.1
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  dots_indicator: ^2.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  onesignal_flutter: ^3.3.0
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.0.0
  share_plus: ^3.1.0
  timeago: ^3.2.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
